version: 1
jobs:
  build:
    docker:
      - image: golang:latest
      - image: circleci/mongo
    # branches:
    #   only:
    #     - master
    steps:
      - checkout:
          path: /go/src/shadow
      - run:
          name: Setup Environment & Build
          command: |
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            cd /go/src/shadow
            ls
            dep ensure
            cp internal/config/samples/dev.yaml.sample internal/config/dev.yaml
            go build cmd/api/server.go
            echo "CI passed ^^!"
  deploy-vultr:
    docker:
      - image: kroniak/ssh-client
    only:
      - master
    steps:
      - add_ssh_keys:
          fingerprints:
            - "60:4a:14:05:24:39:e8:32:07:3b:f5:20:8f:ee:d5:23"
      - run: ssh-keyscan 139.180.221.43 >> ~/.ssh/known_hosts
      - run:
          name: Deploy to Vultr
          command: |
            ssh root@139.180.221.43 cd $GOPATH/src/shadow; git pull; pm2 restart shadow
workflows:
  version: 2
  workflow:
    jobs:
    - build
    - deploy-vultr