version: 1
jobs:
  build:
    docker:
      - image: golang:latest
    branches:
      only:
        - master
    steps:
      - checkout:
          path: /go/src/shadow
      - run:
          name: Run
          command: |
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            cd /go/src/shadow
            ls
            dep ensure
            sh ./SERVER.sh