version: 1
jobs:
  build:
    docker:
      - image: golang:latest
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: Run
          command: sh ./SERVER.sh