version: 1
jobs:
  build:
    docker:
      - image: golang:latest
      - image: circleci/mongo
    # branches:
    #   only:
    #     - master
    steps:
      - checkout:
          path: /go/src/shadow
      - run:
          name: Setup Environment & Build
          command: |
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            cd /go/src/shadow
            ls
            dep ensure
            cp internal/config/samples/dev.yaml.sample internal/config/dev.yaml
            go build cmd/api/server.go
            echo "CI passed!"
  deploy-vultr:
    docker:
      - image: kroniak/ssh-client
    branches:
      only:
        - master 
    steps:
      - checkout:
          path: /go/src/shadow
      - run:
          name: Deploy to Vultr
          commands: |
            ssh root@139.180.221.43 pm2 restart shadow