version: 1
jobs:
  build:
    docker:
      - image: golang:latest
    branches:
      only:
        - master
    steps:
      - checkout:
          path: /go/src/shadow
      - run:
          name: Run
          command: |
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            curl https://raw.githubusercontent.com/qrpike/CentOS-6-Quick-Install-Scripts/master/installMongoDB.sh | sh
            cd /go/src/shadow
            ls
            dep ensure
            cp internal/config/samples/dev.yaml.sample internal/config/dev.yaml
            sh ./SERVER.sh