version: 1
jobs:
  build:
    docker:
      - image: golang:latest
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: Run
          command: |
            sudo apt-get install go-dep
            dep ensure
            sh ./SERVER.sh